[package]
name = "rusty-8"
version = "0.1.0"
authors = ["Tony Head <tony.head@dws.la>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
sdl2 = "0.32.1"
